---

- name: Install docker
  yum: 
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io 
    - docker-compose-plugin
    state: present
  register: installation_status     

- name: Start docker service
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: docker
  register: service_status

- name: Copy docker configuration
  template: 
    src: docker-daemon.json.j2 
    dest: /etc/docker/daemon.json
  register: driver_change

- name: Restart Docker
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: docker
  when: driver_change.changed == true
