---

# 设置主机名
- name: Assign inventory name to unconfigured hostnames
  command: "hostnamectl set-hostname {{ inventory_hostname }}"

# 添加本地解析
- name: Add local resolution to /etc/hosts
  template: src=hosts.conf.j2 dest=/etc/hosts
  
# 配置 selinux
- name: Off SELinux
  command:  /usr/sbin/setenforce 0

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

#- name: Disable SELinux
#  selinux:
#    state: disabled

# 禁用firewalld防火墙
- name: Disable firewalld
  service: name=firewalld state=stopped enabled=no

# 配置DNS
- name: Set DNS 
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

# 配置yum源
- name: Copy yum files
  copy: src={{item.src}} dest=/etc/yum.repos.d/{{item.dest}}
  with_items:
    - { src: 'CentOS-Base.repo' , dest: 'CentOS-Base.repo' }
    - { src: 'epel.repo' , dest: 'epel.repo'  }
    - { src: 'docker-ce.repo' , dest: 'docker-ce.repo'  }
    - { src: 'kubernetes.repo' , dest: 'kubernetes.repo'  }
  notify:
  - yum clean all and yum repolist


#- name: Make sure Chrony is stopped and disable
#  service: name=chronyd state=stopped enabled=no

  #- name: set timezone
  #  shell: timedatectl set-timezone Asia/Shanghai

# 配置ntp时间同步
- name: Install NTP
  yum: name=ntp state=installed

- name: Copy NTP configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntpd service

#- name: Kernel settings
#  copy: src={{item.src}} dest={{item.dest}} owner=root group=root mode=755
#  with_items:
#    - { src: 'sysctl-k8s.conf' , dest: '/etc/sysctl.d/k8s.conf'}
#  notify:
#  - load kernel settings

# 内核设置
- name: Enable ip forwarding
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable ipv6 forwarding
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Enable ipv6 forwarding
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Set vm.swappiness if needed
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: vm.swappiness
    value: "1"
    state: present
    reload: yes

- name: Ensure kube-bench parameters are set
  sysctl:
    sysctl_file: /etc/sysctl.d/bridge-nf-call.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: vm.overcommit_memory, value: 1 }
    - { name: kernel.panic, value: 10 }
    - { name: kernel.panic_on_oops, value: 1 }

# 安装ipvs
- name: Install ipvsadm
  yum: name=ipvsadm state=present

- name: Load ipvs module
  copy: src={{item.src}} dest={{item.dest}} owner=root group=root mode=755
  with_items:
    - { src: 'ipvs.modules' , dest: '/etc/sysconfig/modules/ipvs.modules' }
  notify:
  - source ipvs modules

# 禁用 swap
- name:  Swap | Comment swapfile from /etc/fstab
  shell: sed -i '/swap/s/.*/#&/g' /etc/fstab

- name: Swap | Disable swap
  command: /sbin/swapoff -a

# 优化sshd服务
- name: SSH | Set UseDNS no from /etc/ssh/sshd_config
  shell: grep "^UseDNS no" /etc/ssh/sshd_config || sed -i '/UseDNS/s/.*/UseDNS no/g' /etc/ssh/sshd_config
  notify:
  - restart sshd service