---

# 内核设置
- name: Enable ip forwarding
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable ip bridge for iptables 
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: yes

- name: Enable ipv6 bridge for ip6tables 
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    state: present
    reload: yes
