---

- name: Install docker
  yum: 
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io 
    - docker-compose-plugin
    state: present
  register: installation_status     

- name: "Installation Status"
  debug:
    msg: "Docker Installation Code  -> {{ installation_status.rc }}"

- name: Start docker service
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: docker
  register: service_status

- name: "Service Status"
  debug:
    msg: "Docker Service Code -> {{ service_status.state }}"

- name: Creates directory /etc/docker
  file: path=/etc/docker state=directory

- name: "Changing the driver in the docker"
  copy:
   content: |
         {
           "exec-opts": ["native.cgroupdriver=systemd"],
             "log-driver": "json-file",
             "log-opts": {
               "max-size": "100m"
             },
             "storage-driver": "overlay2",
             "storage-opts": [
               "overlay2.override_kernel_check=true"
             ]
         }
   dest: /etc/docker/daemon.json
  register: driver_change

- name: "Driver Change Info"
  debug:
    msg: "is Docker Driver Changed ? -> {{ driver_change.failed }}"

- name: "Restarting Docker"
  service:
    name: docker
    state: restarted
  when: driver_change.changed == true



