---

# 内核设置
- name: Enable ip forwarding
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable ip bridge for iptables 
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: yes

- name: Enable ipv6 bridge for iptables 
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    state: present
    reload: yes

- name: Set vm.swappiness if needed
  sysctl:
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    name: vm.swappiness
    value: "0"
    state: present
    reload: yes

- name: Ensure kube-bench parameters are set
  sysctl:
    sysctl_file: /etc/sysctl.d/bridge-nf-call.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: vm.overcommit_memory, value: 1 }
    - { name: kernel.panic, value: 10 }
    - { name: kernel.panic_on_oops, value: 1 }