---
# tasks file for ntp-client
#- name: Make sure Chrony is stopped and disable
#  service: name=chronyd state=stopped enabled=no

  #- name: set timezone
  #  shell: timedatectl set-timezone Asia/Shanghai

- name: Install NTP
  yum: name=ntp state=installed

- name: Copy over the NTP configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntpd service
