---
- name: Create a directory if it does not exist
  file:
    path: /tmp/token
    state: directory
    mode: '0755'
  when: inventory_hostname == groups['kube_control_plane'][0]
  
- name: Get token info
  shell: kubeadm --kubeconfig  /etc/kubernetes/admin.conf token create --print-join-command
  when: inventory_hostname == groups['kube_control_plane'][0]
  register: token_info
- debug: 
    var: token_info.stdout
    verbosity: 0

- name: Get key info
  shell: kubeadm --kubeconfig  /etc/kubernetes/admin.conf init phase upload-certs --upload-certs | tail -1
  when: inventory_hostname == groups['kube_control_plane'][0]
  register: key_info
- debug: 
    var: key_info.stdout
    verbosity: 0

- name: Get token and key command
  script: echo "{{token_info.stdout}} --control-plane --certificate-key {{key_info.stdout}}" > /tmp/join-master.sh
  when: inventory_hostname == groups['kube_control_plane'][0]


- name: Get token
  script: echo "{{token_info.stdout}}" > /tmp/join-worker.sh
  when: inventory_hostname == groups['kube_control_plane'][0]