---

- name: Check if ca.crt exists.
  stat:
    path: "/etc/kubernetes/pki/ca.crt"
  register: ca_file_check

- name: Install nginx packages
  yum:
    name:
      - nginx
      - nginx-mod-stream
    state: present
  register: instal_nginx_proxy
  when: not ca_file_check.stat.exists

- name: Config nginx-proxy 
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    mode: 0755
    backup: yes
  register: config_nginx_proxy
  when: not ca_file_check.stat.exists or instal_nginx_proxy is changed

- name: Start nginx service
  systemd:
    state: started
    daemon-reload: "{{ config_nginx_proxy is changed }}"
    enabled: yes
    name: nginx
  when: not ca_file_check.stat.exists or instal_nginx_proxy is changed or config_nginx_proxy is changed

- name: Set iptables port forwarding
  shell: iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport {{loadbalancer_apiserver_port}} -j DNAT --to 127.0.0.1:7443
  when: config_nginx_proxy is changed
  register: config_iptables

- name: Copy script to master nodes
  copy:
    src: "/tmp/master-join-token.sh"
    dest: "/tmp/master-join-token.sh"
    owner: root
    mode: 0755
  when: not ca_file_check.stat.exists or config_nginx_proxy is changed

- name: Run join master node script only if ca.crt does not exist
  script: /tmp/master-join-token.sh --some-argument 1234
  args:
    creates: /etc/kubernetes/pki/ca.crt
  register: master_join_info
- debug: 
    var: master_join_info.stdout_lines

- name: Clear iptables port forwarding
  shell: iptables -t nat -F
  when:  config_iptables is changed or master_join_info is changed

- name: Delete script file
  file:
    path: /tmp/master-join-token.sh
    state: absent
  when: master_join_info is changed

- name: Create directories kube
  file: 
    path: /root/.kube 
    state: directory 
    owner: root 
    group: root
  when: master_join_info is changed

- name: Configure kube
  copy: 
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config 
    remote_src: yes 
    owner: root 
    group: root
  when: master_join_info is changed

- name:  Configure kubectl tools
  shell: echo -e 'source <(kubectl completion bash)\nalias k=kubectl\ncomplete -F __start_kubectl k' > /etc/profile.d/kubectl.sh
  when: master_join_info is changed

- name: Remove nginx package
  yum:
    name:
      - nginx
      - nginx-mod-stream
    state: absent
  when: instal_nginx_proxy is changed or master_join_info is changed