---

- name: Install Kubernete packages
  yum: 
    name:
    - kubeadm-{{kubernetes_version}}
    - kubectl-{{kubernetes_version}}
    - kubelet-{{kubernetes_version}}
    state: present
    disable_excludes: kubernetes
  notify: restart kubelet service

- name: Start kubelet service
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: kubelet

