---
- name: Copy metrics-server-ha.yaml file to master node
  template: src=metrics-server-ha.yaml.j2 dest=/etc/kubernetes/metrics-server-ha.yaml
  when: inventory_hostname == groups['kube_control_plane'][0]
  
- name: Install metrics-server
  shell: kubectl --kubeconfig  /etc/kubernetes/admin.conf apply -f /etc/kubernetes/metrics-server-ha.yaml
  when: inventory_hostname == groups['kube_control_plane'][0]
