---

# 配置 selinux
- name: Set SELinux bool false
  command:  /usr/sbin/setenforce 0

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

#- name: Disable SELinux
#  selinux:
#    state: disabled