---
- import_tasks: 0010-sshd.yml
- import_tasks: 0020-hostname.yml
- import_tasks: 0030-etchosts.yml
- import_tasks: 0040-swapoff.yml
- import_tasks: 0050-selinux.yaml
- import_tasks: 0060-firewalld.yaml
- import_tasks: 0070-dns.yml
- import_tasks: 0080-yum.yml
- import_tasks: 0090-ntp.yml
- import_tasks: 0100-module.yml
- import_tasks: 0110-sysctl.yml
